[project]
name = "laboratory_management"
authors = [{ name = "iMyTest", email = "mingxingma@gmail.com" }]
description = "SENAITE-inspired LIMS for ERPNext"
requires-python = ">=3.11"
dynamic = ["version"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"
